export const routePaths = {
  home: "/",
  services: "/services",
  login: "/login",
  register: "/register",
  profile: "/profile",
  clientHome: "/client-home",
  myBookings: "/client/bookings",
  providerHome: "/provider-home",
  providerSetup: "/provider/setup",
  providerBookings: "/provider/bookings",
  providerAvailability: "/provider/availability",
  providerVerification: "/provider/verification",
  adminHome: "/admin-home",
  dashboard: "/dashboard",
  serviceDetails: "/services/:id",
} as const;
