export const routePaths = {
  home: "/",
  services: "/services",
  login: "/login",
  register: "/register",
  profile: "/profile",
  clientHome: "/client-home",
  myBookings: "/client/bookings",
  favorites: "/client/favorites",
  providerHome: "/provider-home",
  providerSetup: "/provider/setup",
  providerServices: "/provider/services",
  providerServiceCreate: "/provider/services/new",
  providerServiceEdit: "/provider/services/:id/edit",
  providerBookings: "/provider/bookings",
  providerAvailability: "/provider/availability",
  providerVerification: "/provider/verification",
  adminHome: "/admin-home",
  adminDashboard: "/admin/dashboard",
  adminProviders: "/admin/providers",
  dashboard: "/dashboard",
  serviceDetails: "/services/:id",
} as const;
